version: '3.9'

services:
  parking-node:
    image: postgres:12.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: parking2
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: password
      