version: '3.9'

services:
  parking-node:
    image: postgres:12.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: parking2
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: password
  authentication:
    image: quay.io/keycloak/keycloak:25.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=test
    volumes:
      - ./keycloak_data/parking-realm.json:/opt/keycloak/data/import/parking-realm.json
    command:
      - start-dev
      - --import-realm
      